ApplicationName: <APP_NAME>
EnvironmentName: <APP_NAME>-<STAGE>
VersionLabel: <APP_VERSION>
SolutionStackName: '64bit Amazon Linux 2 v5.6.0 running Node.js 16'
OptionSettings:
- ResourceName: 'test'  # A unique resource name for the option setting.
  Namespace: 'teste' # A unique namespace that identifies the option's associated AWS resource.
  OptionName: 'teste' # The name of the configuration option.
  Value: 'teste' # The current value for the configuration option.
